### PR TITLE
Save workspace cache when run failed

### LINKED ISSUE #632: Workspace cache is not saved when scala-steward run fails
At the moment workspace cache is saved only after a successful run at the very end of `try` block
https://github.com/scala-steward-org/scala-steward-action/blob/2763313e6149238002decdaa10ce630868ab2822/src/action/main.ts#L86

So when one of your repos becomes archived or your app token expires after 1 hour (https://github.com/scala-steward-org/scala-steward-action/issues/625) the whole run fails and the cache is not saved. The problem is that on subsequent runs it needs to start from scratch and check all the repos again, even though they have already been successfully updated before.

### PR DESCRIPTION
**Pull request by EnviousSwan**
Fixes #632

Cache from previously failed attempts is restored
And then it's also saved if current attempt fails

image

### CODE REVIEW

**Review by exoego — APPROVED** [review]
The change makes sense to me.

**Comment by exoego** [comment]
Thanks!

File: src/action/main.ts [hunk 1]
```diff
@@ -51,39 +51,41 @@ async function run(): Promise<void> {
...
+    }
 
     if (files.existsSync(workspace.runSummary_md)) {
       logger.info(`✓ Run Summary file: ${workspace.runSummary_md}`)
 
       const summaryMarkdown = files.readFileSync(workspace.runSummary_md, 'utf8')
       await core.summary.addRaw(summaryMarkdown).write()
     }
-
-    await workspace.saveWorkspaceCache()
```
Comment (rtyley) [inline src/action/main.ts:86]: Oh, small problem here! The `saveWorkspaceCache()` method **deletes** temporary files (like `run-summary.md`) before saving the cache, and moving `saveWorkspaceCache()` to _before_ the run-summary processing-code unfortunately means that the `run-summary.md` is deleted before it's even read..!

See this PR for the fix:

* https://github.com/scala-steward-org/scala-steward-action/pull/652
